name: app_review
description: Request and Write Reviews and Open Store Listing for Android and iOS in Flutter.
version: 0.1.1+1
author: Rody Davis <rody.davis.jr@gmail.com>
homepage: https://github.com/AppleEducate/plugins

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http: ^0.12.0+2
  package_info: ^0.4.0+2
  url_launcher: ^5.0.2
  flutter:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    androidPackage: com.appleeducate.appreview
    pluginClass: AppReviewPlugin
