name: contact_picker
description: Flutter plugin for selecting contacts with the native UI and then working with the contacts object.
authors:
  - Flutter Team <flutter-dev@googlegroups.com>
  - Rhodes Davis Jr. <rody.davis.jr@gmail.com>
homepage: https://github.com/AppleEducate/plugins
version: 0.0.6+1

environment:
  sdk: ">=2.1.0 <3.0.0"

flutter:
  plugin:
    androidPackage: com.appleeducate.flutter.contactpicker
    pluginClass: ContactPickerPlugin

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  video_player:
  flutter_test:
    sdk: flutter

