name: lets_meet_flutter
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  fluro: 
  sensors: 
  validate: 
  image_picker: 
  image_cropper: 
  country_code_picker: 
  # flutter_country_picker: ^0.0.1
  place_picker: ^0.9.10
  # flutter_places_dialog: ^1.0.3  
  # flutter_chameleon: ^0.1.4
  flutter_swiper: 
  shared_preferences: 
  dio: 1.0.13
  datetime_picker_formfield:
  # map_view: ^0.0.14
  cirrus_map_view: 
  uri:
  diacritic: 
  url_launcher: 
  firebase_messaging: 
  share: 
  flutter_html: ^0.11.0
  flutter_facebook_login: 
  google_sign_in: 
  http: 
  badges: 
  flutter_advanced_networkimage: 
  photo_view: 
  flutter_cupertino_date_picker: 
  flutter_datetime_picker: 
  firebase_dynamic_links: ^0.5.0+8
  
  

  
  




dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - images/
    - images/backgroundNew.png
    - images/placeholder.png
    
    

  
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: GIcons
      fonts:
        - asset: font/GIcons.ttf
    - family: GCIcon
      fonts:
        - asset: font/GCIcon.ttf
    - family: Flutter_0824_icons
      fonts:
        - asset: font/Flutter_0824_icons.ttf 
    - family: Flutter_0917_icons
      fonts:
        - asset: font/Flutter_0917_icons.ttf 
    - family: MyFlutterApp
      fonts:
        - asset: font/MyFlutterApp.ttf
    - family: Flutter_1101
      fonts:
        - asset: font/Flutter_1101.ttf
    - family: HelveticaNeue
      fonts:
        - asset: font/helveticalNeue/HelveticaNeue.ttf          
        - asset: font/helveticalNeue/HelveticaNeueMedium.ttf
          weight: 300        
        - asset: font/helveticalNeue/HelveticaNeueLight.ttf
          weight: 100 

 
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
