name: flutter_ar
description: A Flutter plugin to wrap ARKit and ARCore.
version: 0.0.1
author: Rody Davis Jr <rody.davis.jr@gmail.com>
homepage: https://github.com/AppleEducate/plugins

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  arkit_plugin: ^0.1.0
  arcore_plugin: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
 
