name: flutter_parallax
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
   - assets/parallax0.png
   - assets/parallax1.png
   - assets/parallax2.png
   - assets/parallax3.png
   - assets/parallax4.png
   - assets/parallax5.png
   - assets/parallax6.png
   - assets/parallax7.png
   - assets/parallax8.png

  fonts:
    - family: Montserrat-Extralight
      fonts:
        - asset: fonts/Montserrat-ExtraLight.ttf

    - family: Montserrat-Medium
      fonts:    
        - asset: fonts/Montserrat-Medium.ttf
