name: contact_picker_example
description: Demonstrates how to use the contact_picker plugin.
author: Rhodes Davis Jr <rody.davis.jr@gmail.com>

dependencies:
  simple_permissions: ^0.1.6
  flutter:
    sdk: flutter
  contact_picker:
    path: ../

flutter:
  uses-material-design: true

